# Generated by Django 4.2.6 on 2023-10-24 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='OptionalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionalContent', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('simpleData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createdata.simpledata')),
            ],
        ),
    ]
