# Generated by Django 4.2.7 on 2023-11-02 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('createdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpledata',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
